services:
  node-app:
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "4000:4000"
    networks:
      - myNetwork
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
    
  postgres:
    image: postgres:16-alpine
    container_name: mypostgres
    networks:
      - myNetwork
    volumes:
      - myVolume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydatabase

networks:
  myNetwork:
    external: true

volumes:
  myVolume:
    external: true